export { default as Home } from './home/home'
export { default as Blogs } from './blogs/blogs'
export { default as Blog } from './blog/blog'
export { default as Product } from './product/productInfo'
export { default as SignUp } from './sign-up/sign-up'
export { default as Profil } from './profil/profil'
export { default as Reset } from './resetpassword/reset';
export { default as Entercode } from './entercode/entercode';
export { default as CreateStore } from './createStore/createStore';
export { default as Store } from './Stores/store';
export { default as Products } from './products/products';
export { default as Cart }  from './cart/cart';
export { default as WishList } from './wishlist/wishlist';
export { default as OneStore } from './store/store';